---
- hosts: localhost
  tasks:
    - homebrew:
        name: ['git',
               'htop',
               'kubectl',
               'git-lfs',
               'macvim',
               'minikube',
               'watch',
               'p7zip',
               'imagemagick',
               'gh',
               'pv'
              ]
    - homebrew_cask:
        name: "{{ item }}"
      with_items:
        - spectacle
        - visual-studio-code
        - firefox
        - opera
        - iterm2
        - anki
        - deepl
        - spotify
        - libreoffice
        - kindle
        - calibre
        - vagrant
        - notion
        - coconutbattery
        - vlc
    - name: git lfs check
      command: git lfs -v
      register: git_lfs_check
    - name: install git lfs
      when: git_lfs_check is failed
      command: git lfs install
               
