---
- hosts: localhost
  tasks:
    - name: check if brew is installed
      command: brew -v
      register: brew_check
    - name: install brew
      when: brew_check is failed
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - name: installing homebrew packages
      homebrew:
        name: ['git',
               'htop',
               'kubectl',
               'git-lfs',
               'macvim',
               'go',
               'minikube'
              ]
    - name: installing homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - spectacle
        - visual-studio-code
        - firefox
        - opera
        - iterm2
        - anki
        - google-cloud-sdk
        - postman
        - deepl
        - spotify
        - telegram
        - whatsapp
        - megasync
        - libreoffice
        - kindle
        - calibre
        - virtualbox
        - virtualbox-extension-pack
        - vagrant
    - name: git lfs check
      command: git lfs -v
      register: git_lfs_check
    - name: install git lfs
      when: git_lfs_check is failed
      command: git lfs install
               
