---
- hosts: localhost
  tasks:
    - homebrew:
        name:
          [
            "git",
            "git-gui",
            "htop",
            "kubectl",
            "macvim",
            "minikube",
            "helm",
            "watch",
            "p7zip",
            "imagemagick",
            "gh",
            "pv",
            "openjdk",
            "jq",
            "yq",
          ]
    - homebrew_cask:
        name: "{{ item }}"
      with_items:
        - spectacle
        - visual-studio-code
        - firefox
        - opera
        - iterm2
        - anki
        - deepl
        - spotify
        - libreoffice
        - kindle
        - calibre
        - vlc
