---
- hosts: localhost
  tasks:
    - homebrew:
        name:
          [
            "git",
            "git-gui",
            "glab"
            "gh",
            "htop",
            "kubectl",
            "macvim",
            "watch",
            "p7zip",
            "imagemagick",
            "pv",
            "openjdk",
            "jq",
            "yq",
            "gpg",
            "mise",
            "oci-cli",
            "glow"
          ]
    - homebrew_tap:
        name: homebrew/cask-fonts
    - homebrew_cask:
        name: "{{ item }}"
      with_items:
        - spectacle
        - rectangle
        - visual-studio-code
        - firefox
        - iterm2
        - anki
        - deepl
        - spotify
        - libreoffice
        - kindle
        - calibre
        - vlc
        - fork
        - tableplus
        - megasync
        - font-fira-code
        - portfolioperformance
        - manyverse
        - whatsapp
        - telegram
        - slack
        - zoom
        - 1password-cli
        - todoist
        - browserosaurus
        - google-cloud-sdk
        - clipy
        - drivedx
